theme: jekyll-theme-hacker

show_downloads: false
is_project_page: true

# Name of website
title: Cyber Defence
description: Specifically focuses on defending against external threats and attacks.
# Your name to show in the footer
author: PhD Researcher

header_pages:
  - index.html
  - my_awesome_lists.md
  - computer_science.md
  - cybersecurity.md
  - development_toolkit.md
  - online_malware_anaysis_tools.md
  - vulnerability_research.md
  - threat_modeling.md
  - cybersecurity_in_belgium.md
  - aboutme.md
